### ISSUE TITLE
Attempting to create a node-pool with required spec missing from config file results in segmentation violation

### ISSUE THREAD

**Issue by nickperry** [vmware-tanzu/tanzu-framework#1778]
**Bug description**

Attempting to create a node-pool with required spec missing from config file results in segmentation violation.

**Affected product area (please put an X in all that apply)**

- [ X ] APIs
- [ ] Addons
- [ X ] CLI
- [ X ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

Attempting to create a node-pool with any missing mandatory configuration should be handled gracefully rather than just causing a segmentation violation.

**Steps to reproduce the bug**

```
echo "name: foo" > foo.yaml
tanzu cluster node-pool set nv8-wl-01 -f foo.yaml
```

**Version** (include the SHA if the version is not obvious)

v0.11.1

**Environment where the bug was observed (cloud, OS, etc)**
Vsphere

**Relevant Debug Output (Logs, manifests, etc)**
```
tanzu cluster node-pool set nv8-wl-01 -f foo.yaml
Using machine deployment nv8-wl-01-md-0 as baseline for new node pool
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x26e722d]

goroutine 1 [running]:
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/client.DoSetMachineDeployment(0x3ac3098, 0xc0009c1ae0, 0xc0007c6300, 0x0, 0x0)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkg/client/machine_deployment.go:176 +0x142d
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/client.(*TkgClient).SetMachineDeployment(0xc0007df110, 0xc0007c6300, 0xc000a49b01, 0xc0007c6300)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkg/client/machine_deployment.go:111 +0x145
github.com/vmware-tanzu/tanzu-framework/pkg/v1/tkg/tkgctl.(*tkgctl).SetMachineDeployment(0xc0001ae380, 0xc0007c6300, 0x200, 0x2a62a00)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/tkg/tkgctl/machine_deployment.go:25 +0x42
main.SetNodePool(0xc000099400, 0x7ffdbbf845a2, 0x9, 0xc000a49cd0, 0x0)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/cmd/cli/plugin/cluster/set_node_pool.go:78 +0x38f
main.runSetNodePool(0x53b2ba0, 0xc0009c5f20, 0x1, 0x3, 0x0, 0x0)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/cmd/cli/plugin/cluster/set_node_pool.go:51 +0x8b
github.com/spf13/cobra.(*Command).execute(0x53b2ba0, 0xc0009c5ef0, 0x3, 0x3, 0x53b2ba0, 0xc0009c5ef0)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000516c80, 0xc000a49f20, 0xb, 0xb)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/vmware-tanzu/tanzu-framework/pkg/v1/cli/command/plugin.(*Plugin).Execute(...)
        /go/src/cayman-tanzu-framework/tanzu-framework/src/pkg/v1/cli/command/plugin/plugin.go:54
main.main()
        /go/src/cayman-tanzu-framework/tanzu-framework/src/cmd/cli/plugin/cluster/main.go:56 +0x267
Error: exit status 2

✖  exit status 2
```

**Comment by tenczar** [comment]
Hey @nickperry, what version of tanzu cli are you running? The main branch does not have any code on line 176, so I'm not sure how that would panic.

**Comment by nickperry** [comment]
> Hey @nickperry, what version of tanzu cli are you running? The main branch does not have any code on line 176, so I'm not sure how that would panic.

@tenczar 1.5.1 (v0.11.1)

**Comment by tenczar** [comment]
So this was original fixed back in Dec https://github.com/vmware-tanzu/tanzu-framework/pull/1302. It did miss the train for the 0.11.0 release, but it also seems to have missed the boat for the TKG 1.5 release (it is fixed in 1.4.2). I will work on getting this ported back to 0.11.2

**Comment by navidshaikh** [comment]
@tenczar: See #1822 for cherry-pick of the fix in `release-0.11` branch.
