### ISSUE TITLE
panic on `tanzu package installed status`

### ISSUE THREAD

**Issue by clebs** [vmware-tanzu/tanzu-framework#4475]
**Bug description**
When running the `tanzu package installed status` CLI command without providing a package name, it panics. 

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (X) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- ( ) User Experience
- ( ) Developer Experience

**Expected behavior**

Input is validated and a proper error message is printed asking to provide a package name.

**Steps to reproduce the bug**

Run `tanzu package installed status`

**Version** (include the SHA if the version is not obvious)
version: v0.28.0
buildDate: 2023-02-03
sha: 3c34115bc-dirty

**Environment where the bug was observed (cloud, OS, etc)**
Mac OSX

**Relevant Debug Output (Logs, manifests, etc)**
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/package/installed.(*StatusOptions).Run(0xc000126210?, {0x3969940?, 0xc000330240?, 0x39385a0?})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/package/installed/status.go:64 +0x417
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/package/installed.NewStatusCmd.func1(0xc000033080?, {0x3969940?, 0xa?, 0xc00013eab3?})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/package/installed/status.go:40 +0x25
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd.configureGlobalFlags.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/kctrl.go:141 +0xce
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00023bb80?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc00023bb80, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000199400)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/vmware-tanzu/tanzu-framework/cli/runtime/plugin.(*Plugin).Execute(...)
	/go/src/cayman-tanzu-framework/tanzu-framework/src/cli/runtime/plugin/plugin.go:60
main.main()
	/go/src/cayman-tanzu-framework/tanzu-framework/src/cmd/cli/plugin/package/main.go:44 +0x92
```

**Comment by clebs** [comment]
Moving the issue to the right repository: https://github.com/carvel-dev/kapp-controller/issues/1160
